#!/bin/bash

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
INCLUDEDIR="${SCRIPTDIR}/include"

DIRECTORY="$PWD"

C_INIT=0
C_BUILD=0
C_DEPLOY=0
C_START=0
C_STOP=0
C_STATUS=0
C_DELETE=0
C_SHELL=0
C_LOG=0

source ${INCLUDEDIR}/os_detect
source ${INCLUDEDIR}/common

while test $# -gt 0; do
	case "$1" in
		-v|--version|version)
			echo "  - version: $GADGET_VERSION"
			exit 0
			;;
		-V|--verbose|verbose)
			echo "  - verbose mode: ENGAGE"
			shift
			;;
		-h|--help|help)
			echo "  - help                                                             "
			echo "    Flags:                                                           "
			echo "      -v | --version   | version      [ show this utility's version ]"
			echo "      -V | --verbose   | verbose      [ more explicit output        ]"
			echo "      -h | --help      | help         [ print help text             ]"
			echo "      -C | --directory |              [ specify a foreign directory ]"
			echo "    Commands:                                                        "
			echo "      init                            [ create project skeleton     ]"
			echo "      build                           [ build project image         ]"
			echo "      deploy                          [ copy image onto gadget      ]"
			echo "      start                           [ run/create a container      ]"
			echo "      stop                            [ stop/delete a container     ]"
			echo "      status                          [ read container status       ]"
			echo "      delete                          [ remove an image from gadget ]"
			echo "      shell                           [ gain shell access to debug  ]"
			echo "      log                             [ show container's stdout     ]"
			exit 0
			;;
		-C|--directory)
			echo "  - in ${2}"
			DIRECTORY=${2}
			shift 2
			;;
		init)
			C_INIT=1
			echo "  - creating new project"
			shift
			;;
		build)
			C_BUILD=1
			echo "  - building project"
			shift
			;;
		deploy)
			C_DEPLOY=1
			echo "  - deploying project"
			shift
			;;
		start)
			C_START=1
			echo "  - starting container"
			shift
			;;
		stop)
			C_STOP=1
			echo "  - stopping container"
			shift
			;;
		status)
			C_STATUS=1
			echo "  - status"
			shift
			;;
		delete)
			C_DELETE=1
			echo "  - delete container on gadget"
			shift
			;;
		shell)
			C_SHELL=1
			echo "  - entering gadget's shell"
			shift
			;;
		log)
			C_LOG=1
			echo "  - retrieving logs"
			shift
			;;
		*)
			echo "  - unidentified param $ARG"
			exit 1
	esac
	
	COMMANDS=(
		${C_INIT}
		${C_BUILD}
		${C_DEPLOY}
		${C_START}
		${C_STOP}
		${C_STATUS}
		${C_DELETE}
		${C_SHELL}
		${C_LOG}
	)
	
	source ${INCLUDEDIR}/check_cmd_conflict
done

[[ 1 -eq ${C_INIT}   ]] && source ${INCLUDEDIR}/gadget_init   && exit 0
[[ 1 -eq ${C_BUILD}  ]] && source ${INCLUDEDIR}/gadget_build  && exit 0
[[ 1 -eq ${C_DEPLOY} ]] && source ${INCLUDEDIR}/gadget_deploy && exit 0
[[ 1 -eq ${C_START}  ]] && source ${INCLUDEDIR}/gadget_start  && exit 0
[[ 1 -eq ${C_STOP}   ]] && source ${INCLUDEDIR}/gadget_stop   && exit 0
[[ 1 -eq ${C_STATUS} ]] && source ${INCLUDEDIR}/gadget_status && exit 0
[[ 1 -eq ${C_DELETE} ]] && source ${INCLUDEDIR}/gadget_delete && exit 0
[[ 1 -eq ${C_SHELL}  ]] && source ${INCLUDEDIR}/gadget_shell  && exit 0
[[ 1 -eq ${C_LOG}    ]] && source ${INCLUDEDIR}/gadget_log    && exit 0
