#!/bin/bash

MKDIR=${MKDIR:-mkdir}
TOUCH=${TOUCH:-touch}
REQUIRED=( ${MKDIR} ${TOUCH} )

source ${INCLUDEDIR}/check_required

## COMMON VARIABLES
SSH_OPTS="-o ConnectTimeout=5 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
GADGET_VERSION="v1"

function create_directory {
	if [[ ! -d "${1}" ]]; then
		mkdir -p ${1}
		if [ ${?} -ne 0 ]; then
			echo "  ERROR: failed to create directory ${1}"
			exit 1
		fi
	fi
}

function create_file {
	if [[ ! -f "${1}" ]]; then
		touch ${1}
		if [ ${?} -ne 0 ]; then
			echo "  ERROR: failed to create file ${1}"
			exit 1
		fi
	fi
}

function check_directory {
	if [[ ! -d "${1}" ]]; then
		echo "  ERROR: could not locate directory ${1}"
		exit 1
	fi
}

function check_file {
	if [[ ! -f "${1}" ]]; then
		echo "  ERROR: could not locate file ${1}"
		exit 1
	fi
}

function create_new_key {
	## BEGIN NEEDS SAFETY CHECKS
	echo "  First use: generating unique ssh key"
	${SSH_KEYGEN} -t rsa -f ${HOME}/.ssh/gadget_rsa -N ""
	chmod 600 ${HOME}/.ssh/gadget_rsa*
	echo "  Adding new key to keychain"
	${SSH_ADD} ${HOME}/.ssh/gadget_rsa
	## END NEEDS SAFETY CHECKS
}

function gadget_error {
	echo "  ERROR: ${1} w/ ${2} @ ${3}" && exit 1
}
