#!/bin/bash

CAT=${CAT:-cat}
UUIDGEN=${UUIDGEN:-uuidgen}
BASENAME=${BASENAME:-basename}
READLINK=${READLINK:-readlink}
REQUIRED=( ${CAT} ${UUIDGEN} ${BASENAME} ${READLINK} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/common

## Create directory if a custom one was specified, otherwise, using cwd
[ "${DIRECTORY}" != "${PWD}" ] && create_directory ${DIRECTORY}
check_directory  ${DIRECTORY}
create_file      ${DIRECTORY}/gadget.cfg
check_file       ${DIRECTORY}/gadget.cfg
create_file      ${DIRECTORY}/Dockerfile
check_file       ${DIRECTORY}/Dockerfile

## Create scaffolding

echo "project_gadget_version=${GADGET_VERSION}" > ${DIRECTORY}/gadget.cfg
echo "name=$(${BASENAME} $(${READLINK} -e ${DIRECTORY}))" >> ${DIRECTORY}/gadget.cfg
echo "uuid=$(${UUIDGEN})"   >> ${DIRECTORY}/gadget.cfg

${CAT} <<-EOF > ${DIRECTORY}/Dockerfile
FROM armhf/alpine

CMD ["/bin/cat","/etc/os-release"]
EOF

echo "  - done" 1>&3 2>&4
