#!/bin/bash

DOCKER=${DOCKER:-docker}
SSH=${SSH:-ssh}
REQUIRED=( ${DOCKER} ${SSH} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/common

check_directory  ${DIRECTORY}
check_file       ${DIRECTORY}/gadget.cfg

source ${DIRECTORY}/gadget.cfg
${DOCKER} save ${name}_${uuid}-img | ${SSH} root@gadget.local -t "docker load"
