#!/bin/bash

TOUCH=${TOUCH:-touch}
CAT=${CAT:-cat}
UUIDGEN=${UUIDGEN:-uuidgen}
MKDIR=${MKDIR:-mkdir}
BASENAME=${BASENAME:-basename}
READLINK=${READLINK:-readlink}
REQUIRED=( ${TOUCH} ${CAT} ${UUIDGEN} ${MKDIR} ${BASENAME} ${READLINK} )

source ${INCLUDEDIR}/check_required

if [ ! -d ${DIRECTORY} ]; then
	${MKDIR} -p ${DIRECTORY}
fi

${TOUCH} ${DIRECTORY}/gadget.cfg

echo "name=$(${BASENAME} $(${READLINK} -e ${DIRECTORY}))" >> ${DIRECTORY}/gadget.cfg
echo "uuid=$(${UUIDGEN})"   >> ${DIRECTORY}/gadget.cfg

${CAT} <<-EOF > ${DIRECTORY}/Dockerfile
FROM armhf/alpine

CMD ["/bin/sh","-c","'echo hello'"]
EOF
