#!/bin/bash

DOCKER=${DOCKER:-docker}
REQUIRED=( ${DOCKER} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/common

check_directory  ${DIRECTORY}
check_file       ${DIRECTORY}/gadget.cfg
check_file       ${DIRECTORY}/Dockerfile

source ${DIRECTORY}/gadget.cfg
${DOCKER} build -t ${name}_${uuid}-img ${DIRECTORY}

## Error check and report eg. "gadget_build error 0-15"
[ ${?} -ne 0 ] && echo "  - ${BASH_SOURCE##*/} error ${?}-${LINENO}" && exit 1
