#!/bin/bash -ex

UNAME=${UNAME:-uname}
GREP=${GREP:-grep}
REQUIRED=( ${UNAME} ${GREP} )

source ${INCLUDEDIR}/check_required
case "$(uname)" in
	Darwin) OS="darwin";;
	Linux) OS="linux";;
	MSYS32) OS="windows";;
	*)
		echo "  OS version not supported/could not be determined"
		exit 1
		;;
esac
