#!/bin/bash

SSH=${SSH:-ssh}
SSH_KEYGEN=${SSH_KEYGEN:-ssh-keygen}
SSH_ADD=${SSH_ADD:-ssh-add}
SCP=${SCP:-scp}
MKTEMP=${MKTEMP:-mktemp}
CHMOD=${CHMOD:-chmod}
REQUIRED=( ${SSH} ${SSH_KEYGEN} ${SCP} ${MKTEMP} ${CHMOD} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/os_detect

case "${OS}" in
	"darwin" | "linux" )
		IP="192.168.81.1"
		;;
	"windows" )
		IP="192.168.82.1"
		;;
	*)
		echo "  OS version not supported/could not be determined"
		echo "  Unable to set applicable IP address"
		exit 1
		;;
esac

source ${INCLUDEDIR}/common

check_directory		${DIRECTORY}
check_file			${DIRECTORY}/gadget.cfg

source				${DIRECTORY}/gadget.cfg

${SSH} ${SSH_OPTS} root@${IP} -t "echo gadget_probe" &> /dev/null

case "${?}" in
	255)
		echo "  A new key is required [old conflict]"
		${SSH_KEYGEN} -f "${HOME}/.ssh/known_hosts" -R ${IP}
		create_new_key
		;;
	0)
		echo "  ssh connection tested good"
		;;
	*)
		echo "  ERROR: unexpected result at ssh test"
		;;
esac

