#!/bin/bash

SSH=${SSH:-ssh}
SSH_KEYGEN=${SSH_KEYGEN:-ssh-keygen}
SSH_ADD=${SSH_ADD:-ssh-add}
SCP=${SCP:-scp}
MKTEMP=${MKTEMP:-mktemp}
CHMOD=${CHMOD:-chmod}
REQUIRED=( ${SSH} ${SSH_KEYGEN} ${SCP} ${MKTEMP} ${CHMOD} )

source ${INCLUDEDIR}/check_required
source ${INCLUDEDIR}/os_detect

case "${OS}" in
	"darwin" | "linux" )
		IP="192.168.81.1"
		;;
	"windows" )
		IP="192.168.82.1"
		;;
	*)
		echo "  OS version not supported/could not be determined"
		echo "  Unable to set applicable IP address"
		exit 1
		;;
esac

source ${INCLUDEDIR}/common

check_directory		${DIRECTORY}
check_file			${DIRECTORY}/gadget.cfg

source				${DIRECTORY}/gadget.cfg

check_directory		${HOME}/.ssh

[ ! -f ${HOME}/.ssh/gadget_rsa ] && create_new_key

${SSH} ${SSH_OPTS} -oBatchMode=yes -2 -i ${HOME}/.ssh/gadget_rsa root@${IP} -t "echo gadget_probe" &> /dev/null

# 0 if logs in with available ssh keys, 255 if fails
if [ ${?} -ne 0 ]; then
	echo "  This looks like a freshly flashed device..."
	${SSH} ${SSH_OPTS} -oBatchMode=yes -2 -i ${INCLUDEDIR}/id_rsa root@${IP} -t "echo gadget_probe" &> /dev/null
	
	if [ ${?} -ne 0 ]; then
		echo "  Unable to login with local or default credentials, did you leave your keys at home? E:${?}"
		exit 1
	else
		echo "  Copying new key to gadget"
		## future warning: in certain circumstances gadget_rsa will get huge
		${SCP} ${SSH_OPTS} -i ${INCLUDEDIR}/id_rsa ${HOME}/.ssh/gadget_rsa.pub root@${IP}:/root/.ssh/authorized_keys
	fi
fi

